- name: Install System Packages 1
  become: true
  apt:
    name: ["build-essential", "cmake", "libtool", "libtool-bin", "ninja-build", "gettext", "autoconf", "g++", "pkg-config", "unzip", "curl", "doxygen", "btop"]
  tags:
    - install
    - core
    - nvim
- name: Install System Packages 2
  become: true
  apt:
    name: ["i3"]
  tags:
    - install
    - core
- name: Install Clang
  become: true
  apt:
    name: ["clang", "clangd", "clang-12", "clangd-12"]
  tags:
    - install
    - core
    - nvim
- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - install
    - core
- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - install
    - core

